{% set name = "napari-microtubule-analyzer" %}
{% set version = "0.0.1a7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-microtubule-analyzer-{{ version }}.tar.gz
  sha256: 895bf0794d2ed32788572bf33b15634eb037784c1e1282dc950faa5666c5eee6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=42.0.0
    - wheel
  run:
    - magicgui
    - matplotlib-base
    - napari
    - numpy
    - opencv
    - packaging
    - pyefd
    - pyqtgraph
    - python >={{ python_min }}
    - qtpy
    - scikit-image
    - scipy
    - setuptools
    - tifffile
    - tqdm

test:
  imports:
    - napari_microtubule_analyzer
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-microtubule-analyzer
  summary: A plugin to analyze microtubule organization
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/krentzd/napari-microtubule-analyzer

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
